# Generated by Django 5.0.6 on 2024-06-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClasesUFC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
